import { resolveOrderLineItems, type PricedLine } from '@qr/catalog/pricing';
import { sha256Hex } from '@qr/identity/token-digest';
import { generateOrderCode, generatePaymentReference as defaultPaymentReference } from '../codes.ts';
import { readCustomerOrderById, type CustomerOrder } from '../order-read.ts';
import type { OrderLineInput } from '../order-validation.ts';

export type CreateOrderInput = {
  storeId: string;
  tableId: string;
  idempotencyKey: string;
  /** The customer's Secret Link token, generated by the client alongside the idempotency key (phase 3 decision #5). */
  orderToken: string;
  items: OrderLineInput[];
  /** Test seam for reference collisions. */
  generatePaymentReference?: () => string;
};

export type CreateOrderResult =
  | { ok: true; replayed: boolean; order: CustomerOrder }
  | { ok: false; code: 'items_unavailable'; items: { productId: string; code: string }[] }
  | { ok: false; code: 'idempotency_conflict' | 'order_token_in_use' | 'total_mismatch' | 'payment_reference_exhausted' };

export type OrderDraft = {
  orderId: string;
  storeId: string;
  tableId: string;
  orderCode: string;
  paymentReference: string;
  currency: string;
  totalAmountMinor: number;
  lines: (PricedLine & { notes: string })[];
  idempotencyKey: string;
  orderToken: string;
};

const MAX_CODE_ATTEMPTS = 3;
// Constraint failures that mean "draw new codes and try again".
const CODE_COLLISION = /UNIQUE constraint failed: orders\.store_id, orders\.(?:payment_reference|order_code)/;
const KEY_TAKEN = /UNIQUE constraint failed: order_idempotency\.store_id, order_idempotency\.request_key/;
const TOKEN_TAKEN = /UNIQUE constraint failed: order_access\.store_id, order_access\.capability_digest/;
// The batch's final assertion nulls orders.order_code when the stored total disagrees with the stored lines.
const TOTAL_ASSERTION_FAILED = /NOT NULL constraint failed: orders\.order_code/;

/**
 * One atomic batch: order, lines (price snapshots), capability, idempotency ledger, then an assertion that aborts
 * everything unless the total equals the sum of the stored lines (D11.4).
 */
export async function createOrderStatements(db: D1Database, draft: OrderDraft): Promise<D1PreparedStatement[]> {
  const capabilityDigest = await sha256Hex(draft.orderToken);
  return [
    db
      .prepare(
        `INSERT INTO orders (id, store_id, order_code, table_id, status, currency, total_amount_minor, payment_method, payment_reference)
         VALUES (?, ?, ?, ?, 'pending_payment', ?, ?, 'vietqr', ?)`,
      )
      .bind(draft.orderId, draft.storeId, draft.orderCode, draft.tableId, draft.currency, draft.totalAmountMinor, draft.paymentReference),
    ...draft.lines.map((line, position) =>
      db
        .prepare(
          `INSERT INTO order_items (id, store_id, order_id, product_id, product_name_snapshot, quantity, unit_price_snapshot_minor,
                                    line_total_minor, currency, notes, position)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        )
        .bind(
          crypto.randomUUID(),
          draft.storeId,
          draft.orderId,
          line.productId,
          line.productName,
          line.quantity,
          line.unitPriceMinor,
          line.lineTotalMinor,
          draft.currency,
          line.notes,
          position,
        ),
    ),
    db
      .prepare('INSERT INTO order_access (id, store_id, order_id, capability_digest) VALUES (?, ?, ?, ?)')
      .bind(crypto.randomUUID(), draft.storeId, draft.orderId, capabilityDigest),
    db
      .prepare('INSERT INTO order_idempotency (id, store_id, request_key, capability_digest, order_id) VALUES (?, ?, ?, ?, ?)')
      .bind(crypto.randomUUID(), draft.storeId, draft.idempotencyKey, capabilityDigest, draft.orderId),
    db
      .prepare(
        `UPDATE orders SET order_code = CASE
           WHEN status = 'pending_payment'
            AND total_amount_minor = (SELECT COALESCE(SUM(line_total_minor), -1) FROM order_items WHERE store_id = ? AND order_id = ?)
           THEN order_code ELSE NULL END
         WHERE store_id = ? AND id = ?`,
      )
      .bind(draft.storeId, draft.orderId, draft.storeId, draft.orderId),
  ];
}

async function replay(db: D1Database, input: CreateOrderInput): Promise<CreateOrderResult | null> {
  const ledger = await db
    .prepare('SELECT order_id, capability_digest FROM order_idempotency WHERE store_id = ? AND request_key = ?')
    .bind(input.storeId, input.idempotencyKey)
    .first<{ order_id: string; capability_digest: string }>();
  if (!ledger) return null;
  if (ledger.capability_digest !== (await sha256Hex(input.orderToken))) return { ok: false, code: 'idempotency_conflict' };
  const order = await readCustomerOrderById(db, input.storeId, ledger.order_id);
  if (!order) throw new Error(`Idempotency ledger points at missing order ${ledger.order_id}`);
  return { ok: true, replayed: true, order };
}

/** Creates a pending_payment order priced entirely on the server, or replays the one bound to the idempotency key. */
export async function createOrder(db: D1Database, input: CreateOrderInput): Promise<CreateOrderResult> {
  const replayed = await replay(db, input);
  if (replayed) return replayed;

  const priced = await resolveOrderLineItems(db, input.storeId, input.items);
  if (!priced.ok) return { ok: false, code: 'items_unavailable', items: priced.rejected };

  const nextReference = input.generatePaymentReference ?? defaultPaymentReference;
  const orderId = crypto.randomUUID();
  for (let attempt = 0; attempt < MAX_CODE_ATTEMPTS; attempt++) {
    const statements = await createOrderStatements(db, {
      orderId,
      storeId: input.storeId,
      tableId: input.tableId,
      orderCode: generateOrderCode(),
      paymentReference: nextReference(),
      currency: priced.currency,
      totalAmountMinor: priced.totalAmountMinor,
      lines: priced.lines.map((line, index) => ({ ...line, notes: input.items[index].notes })),
      idempotencyKey: input.idempotencyKey,
      orderToken: input.orderToken,
    });
    try {
      await db.batch(statements);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      if (CODE_COLLISION.test(message)) continue;
      if (KEY_TAKEN.test(message)) {
        const raced = await replay(db, input);
        if (raced) return raced;
      }
      if (TOKEN_TAKEN.test(message)) return { ok: false, code: 'order_token_in_use' };
      if (TOTAL_ASSERTION_FAILED.test(message)) return { ok: false, code: 'total_mismatch' };
      throw error;
    }
    const order = await readCustomerOrderById(db, input.storeId, orderId);
    if (!order) throw new Error(`Order ${orderId} missing after a committed batch`);
    return { ok: true, replayed: false, order };
  }
  return { ok: false, code: 'payment_reference_exhausted' };
}
